package com.mua.cml.model;

import java.util.ArrayList;
import java.util.List;

public class CmlNationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cml_nation
     *
     * @mbggenerated Thu Jul 20 15:06:36 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cml_nation
     *
     * @mbggenerated Thu Jul 20 15:06:36 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cml_nation
     *
     * @mbggenerated Thu Jul 20 15:06:36 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Thu Jul 20 15:06:36 CST 2017
     */
    public CmlNationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Thu Jul 20 15:06:36 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Thu Jul 20 15:06:36 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Thu Jul 20 15:06:36 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Thu Jul 20 15:06:36 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Thu Jul 20 15:06:36 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Thu Jul 20 15:06:36 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Thu Jul 20 15:06:36 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Thu Jul 20 15:06:36 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Thu Jul 20 15:06:36 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Thu Jul 20 15:06:36 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cml_nation
     *
     * @mbggenerated Thu Jul 20 15:06:36 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNationIdIsNull() {
            addCriterion("nation_id is null");
            return (Criteria) this;
        }

        public Criteria andNationIdIsNotNull() {
            addCriterion("nation_id is not null");
            return (Criteria) this;
        }

        public Criteria andNationIdEqualTo(Long value) {
            addCriterion("nation_id =", value, "nationId");
            return (Criteria) this;
        }

        public Criteria andNationIdNotEqualTo(Long value) {
            addCriterion("nation_id <>", value, "nationId");
            return (Criteria) this;
        }

        public Criteria andNationIdGreaterThan(Long value) {
            addCriterion("nation_id >", value, "nationId");
            return (Criteria) this;
        }

        public Criteria andNationIdGreaterThanOrEqualTo(Long value) {
            addCriterion("nation_id >=", value, "nationId");
            return (Criteria) this;
        }

        public Criteria andNationIdLessThan(Long value) {
            addCriterion("nation_id <", value, "nationId");
            return (Criteria) this;
        }

        public Criteria andNationIdLessThanOrEqualTo(Long value) {
            addCriterion("nation_id <=", value, "nationId");
            return (Criteria) this;
        }

        public Criteria andNationIdIn(List<Long> values) {
            addCriterion("nation_id in", values, "nationId");
            return (Criteria) this;
        }

        public Criteria andNationIdNotIn(List<Long> values) {
            addCriterion("nation_id not in", values, "nationId");
            return (Criteria) this;
        }

        public Criteria andNationIdBetween(Long value1, Long value2) {
            addCriterion("nation_id between", value1, value2, "nationId");
            return (Criteria) this;
        }

        public Criteria andNationIdNotBetween(Long value1, Long value2) {
            addCriterion("nation_id not between", value1, value2, "nationId");
            return (Criteria) this;
        }

        public Criteria andNationNameIsNull() {
            addCriterion("nation_name is null");
            return (Criteria) this;
        }

        public Criteria andNationNameIsNotNull() {
            addCriterion("nation_name is not null");
            return (Criteria) this;
        }

        public Criteria andNationNameEqualTo(String value) {
            addCriterion("nation_name =", value, "nationName");
            return (Criteria) this;
        }

        public Criteria andNationNameNotEqualTo(String value) {
            addCriterion("nation_name <>", value, "nationName");
            return (Criteria) this;
        }

        public Criteria andNationNameGreaterThan(String value) {
            addCriterion("nation_name >", value, "nationName");
            return (Criteria) this;
        }

        public Criteria andNationNameGreaterThanOrEqualTo(String value) {
            addCriterion("nation_name >=", value, "nationName");
            return (Criteria) this;
        }

        public Criteria andNationNameLessThan(String value) {
            addCriterion("nation_name <", value, "nationName");
            return (Criteria) this;
        }

        public Criteria andNationNameLessThanOrEqualTo(String value) {
            addCriterion("nation_name <=", value, "nationName");
            return (Criteria) this;
        }

        public Criteria andNationNameLike(String value) {
            addCriterion("nation_name like", value, "nationName");
            return (Criteria) this;
        }

        public Criteria andNationNameNotLike(String value) {
            addCriterion("nation_name not like", value, "nationName");
            return (Criteria) this;
        }

        public Criteria andNationNameIn(List<String> values) {
            addCriterion("nation_name in", values, "nationName");
            return (Criteria) this;
        }

        public Criteria andNationNameNotIn(List<String> values) {
            addCriterion("nation_name not in", values, "nationName");
            return (Criteria) this;
        }

        public Criteria andNationNameBetween(String value1, String value2) {
            addCriterion("nation_name between", value1, value2, "nationName");
            return (Criteria) this;
        }

        public Criteria andNationNameNotBetween(String value1, String value2) {
            addCriterion("nation_name not between", value1, value2, "nationName");
            return (Criteria) this;
        }

        public Criteria andNationDescIsNull() {
            addCriterion("nation_desc is null");
            return (Criteria) this;
        }

        public Criteria andNationDescIsNotNull() {
            addCriterion("nation_desc is not null");
            return (Criteria) this;
        }

        public Criteria andNationDescEqualTo(String value) {
            addCriterion("nation_desc =", value, "nationDesc");
            return (Criteria) this;
        }

        public Criteria andNationDescNotEqualTo(String value) {
            addCriterion("nation_desc <>", value, "nationDesc");
            return (Criteria) this;
        }

        public Criteria andNationDescGreaterThan(String value) {
            addCriterion("nation_desc >", value, "nationDesc");
            return (Criteria) this;
        }

        public Criteria andNationDescGreaterThanOrEqualTo(String value) {
            addCriterion("nation_desc >=", value, "nationDesc");
            return (Criteria) this;
        }

        public Criteria andNationDescLessThan(String value) {
            addCriterion("nation_desc <", value, "nationDesc");
            return (Criteria) this;
        }

        public Criteria andNationDescLessThanOrEqualTo(String value) {
            addCriterion("nation_desc <=", value, "nationDesc");
            return (Criteria) this;
        }

        public Criteria andNationDescLike(String value) {
            addCriterion("nation_desc like", value, "nationDesc");
            return (Criteria) this;
        }

        public Criteria andNationDescNotLike(String value) {
            addCriterion("nation_desc not like", value, "nationDesc");
            return (Criteria) this;
        }

        public Criteria andNationDescIn(List<String> values) {
            addCriterion("nation_desc in", values, "nationDesc");
            return (Criteria) this;
        }

        public Criteria andNationDescNotIn(List<String> values) {
            addCriterion("nation_desc not in", values, "nationDesc");
            return (Criteria) this;
        }

        public Criteria andNationDescBetween(String value1, String value2) {
            addCriterion("nation_desc between", value1, value2, "nationDesc");
            return (Criteria) this;
        }

        public Criteria andNationDescNotBetween(String value1, String value2) {
            addCriterion("nation_desc not between", value1, value2, "nationDesc");
            return (Criteria) this;
        }

        public Criteria andNationPicIsNull() {
            addCriterion("nation_pic is null");
            return (Criteria) this;
        }

        public Criteria andNationPicIsNotNull() {
            addCriterion("nation_pic is not null");
            return (Criteria) this;
        }

        public Criteria andNationPicEqualTo(String value) {
            addCriterion("nation_pic =", value, "nationPic");
            return (Criteria) this;
        }

        public Criteria andNationPicNotEqualTo(String value) {
            addCriterion("nation_pic <>", value, "nationPic");
            return (Criteria) this;
        }

        public Criteria andNationPicGreaterThan(String value) {
            addCriterion("nation_pic >", value, "nationPic");
            return (Criteria) this;
        }

        public Criteria andNationPicGreaterThanOrEqualTo(String value) {
            addCriterion("nation_pic >=", value, "nationPic");
            return (Criteria) this;
        }

        public Criteria andNationPicLessThan(String value) {
            addCriterion("nation_pic <", value, "nationPic");
            return (Criteria) this;
        }

        public Criteria andNationPicLessThanOrEqualTo(String value) {
            addCriterion("nation_pic <=", value, "nationPic");
            return (Criteria) this;
        }

        public Criteria andNationPicLike(String value) {
            addCriterion("nation_pic like", value, "nationPic");
            return (Criteria) this;
        }

        public Criteria andNationPicNotLike(String value) {
            addCriterion("nation_pic not like", value, "nationPic");
            return (Criteria) this;
        }

        public Criteria andNationPicIn(List<String> values) {
            addCriterion("nation_pic in", values, "nationPic");
            return (Criteria) this;
        }

        public Criteria andNationPicNotIn(List<String> values) {
            addCriterion("nation_pic not in", values, "nationPic");
            return (Criteria) this;
        }

        public Criteria andNationPicBetween(String value1, String value2) {
            addCriterion("nation_pic between", value1, value2, "nationPic");
            return (Criteria) this;
        }

        public Criteria andNationPicNotBetween(String value1, String value2) {
            addCriterion("nation_pic not between", value1, value2, "nationPic");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cml_nation
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 20 15:06:36 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cml_nation
     *
     * @mbggenerated Thu Jul 20 15:06:36 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}