package com.mua.cml.model;

public class CmlNation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cml_nation.nation_id
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    private Long nationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cml_nation.nation_name
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    private String nationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cml_nation.nation_desc
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    private String nationDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cml_nation.nation_pic
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    private String nationPic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cml_nation.nation_id
     *
     * @return the value of cml_nation.nation_id
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    public Long getNationId() {
        return nationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cml_nation.nation_id
     *
     * @param nationId the value for cml_nation.nation_id
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    public void setNationId(Long nationId) {
        this.nationId = nationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cml_nation.nation_name
     *
     * @return the value of cml_nation.nation_name
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    public String getNationName() {
        return nationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cml_nation.nation_name
     *
     * @param nationName the value for cml_nation.nation_name
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    public void setNationName(String nationName) {
        this.nationName = nationName == null ? null : nationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cml_nation.nation_desc
     *
     * @return the value of cml_nation.nation_desc
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    public String getNationDesc() {
        return nationDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cml_nation.nation_desc
     *
     * @param nationDesc the value for cml_nation.nation_desc
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    public void setNationDesc(String nationDesc) {
        this.nationDesc = nationDesc == null ? null : nationDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cml_nation.nation_pic
     *
     * @return the value of cml_nation.nation_pic
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    public String getNationPic() {
        return nationPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cml_nation.nation_pic
     *
     * @param nationPic the value for cml_nation.nation_pic
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    public void setNationPic(String nationPic) {
        this.nationPic = nationPic == null ? null : nationPic.trim();
    }
}