package com.mua.cml.mapper;

import com.mua.cml.model.CmlNation;
import com.mua.cml.model.CmlNationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CmlNationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Mon Jul 17 14:54:34 CST 2017
     */
    int countByExample(CmlNationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Mon Jul 17 14:54:34 CST 2017
     */
    int deleteByExample(CmlNationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Mon Jul 17 14:54:34 CST 2017
     */
    int deleteByPrimaryKey(Long nationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Mon Jul 17 14:54:34 CST 2017
     */
    int insert(CmlNation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Mon Jul 17 14:54:34 CST 2017
     */
    int insertSelective(CmlNation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Mon Jul 17 14:54:34 CST 2017
     */
    List<CmlNation> selectByExample(CmlNationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Mon Jul 17 14:54:34 CST 2017
     */
    CmlNation selectByPrimaryKey(Long nationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Mon Jul 17 14:54:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") CmlNation record, @Param("example") CmlNationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Mon Jul 17 14:54:34 CST 2017
     */
    int updateByExample(@Param("record") CmlNation record, @Param("example") CmlNationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Mon Jul 17 14:54:34 CST 2017
     */
    int updateByPrimaryKeySelective(CmlNation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cml_nation
     *
     * @mbggenerated Mon Jul 17 14:54:34 CST 2017
     */
    int updateByPrimaryKey(CmlNation record);
}