package com.mua.cml.mapper;

import com.mua.cml.model.HfMember;
import com.mua.cml.model.HfMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HfMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_member
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    int countByExample(HfMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_member
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    int deleteByExample(HfMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_member
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    int deleteByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_member
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    int insert(HfMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_member
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    int insertSelective(HfMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_member
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    List<HfMember> selectByExample(HfMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_member
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    HfMember selectByPrimaryKey(Long memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_member
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    int updateByExampleSelective(@Param("record") HfMember record, @Param("example") HfMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_member
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    int updateByExample(@Param("record") HfMember record, @Param("example") HfMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_member
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    int updateByPrimaryKeySelective(HfMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_member
     *
     * @mbggenerated Thu Jul 20 14:17:47 CST 2017
     */
    int updateByPrimaryKey(HfMember record);
}